import type { Preset } from "../types/studio";

export const PRESETS: Preset[] = [
  {
    id: "classic",
    name: "Classic Terminal",
    description: "Eski terminal estetiği",
    icon: "⬛",
    bg: "#0d1117",
    fg: "#c9d1d9",
    settings: {
      charsetId: "standard",
      background: "#0d1117",
      foreground: "#c9d1d9",
      mode: "mono",
      contrast: 1.2,
      brightness: 0,
      invert: false,
      fontSize: 12,
    },
  },
  {
    id: "matrix",
    name: "Green Matrix",
    description: "Yeşil matrix yağmuru",
    icon: "🟢",
    bg: "#000000",
    fg: "#00ff41",
    settings: {
      charsetId: "matrix",
      background: "#000000",
      foreground: "#00ff41",
      mode: "mono",
      contrast: 1.4,
      brightness: 10,
      invert: false,
      fontSize: 11,
    },
  },
  {
    id: "amber",
    name: "Amber CRT",
    description: "Eski CRT monitör turuncu tonu",
    icon: "🟠",
    bg: "#1a0a00",
    fg: "#ff8c00",
    settings: {
      charsetId: "standard",
      background: "#1a0a00",
      foreground: "#ff8c00",
      mode: "mono",
      contrast: 1.3,
      brightness: 5,
      invert: false,
      fontSize: 12,
    },
  },
  {
    id: "neon",
    name: "Cyberpunk Neon",
    description: "Neon pembe siber punk",
    icon: "💜",
    bg: "#0a0010",
    fg: "#ff00ff",
    settings: {
      charsetId: "detailed",
      background: "#0a0010",
      foreground: "#ff00ff",
      mode: "mono",
      contrast: 1.5,
      brightness: 15,
      invert: false,
      fontSize: 10,
    },
  },
  {
    id: "mono",
    name: "Pure Mono",
    description: "Temiz siyah üzerine beyaz",
    icon: "⬜",
    bg: "#000000",
    fg: "#ffffff",
    settings: {
      charsetId: "detailed",
      background: "#000000",
      foreground: "#ffffff",
      mode: "mono",
      contrast: 1.0,
      brightness: 0,
      invert: false,
      fontSize: 11,
    },
  },
  {
    id: "inverted",
    name: "Inverted",
    description: "Ters — beyaz üzerine siyah",
    icon: "🔲",
    bg: "#ffffff",
    fg: "#000000",
    settings: {
      charsetId: "detailed",
      background: "#ffffff",
      foreground: "#000000",
      mode: "mono",
      contrast: 1.0,
      brightness: 0,
      invert: true,
      fontSize: 11,
    },
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Teknik çizim mavisi",
    icon: "🔵",
    bg: "#003366",
    fg: "#7ec8e3",
    settings: {
      charsetId: "box",
      background: "#003366",
      foreground: "#7ec8e3",
      mode: "mono",
      contrast: 1.2,
      brightness: 0,
      invert: false,
      fontSize: 12,
    },
  },
  {
    id: "color",
    name: "Full Color",
    description: "Orijinal renkleriyle renkli ASCII",
    icon: "🌈",
    bg: "#000000",
    fg: "#ffffff",
    settings: {
      charsetId: "detailed",
      background: "#000000",
      foreground: "#ffffff",
      mode: "color",
      contrast: 1.1,
      brightness: 5,
      invert: false,
      fontSize: 10,
      colorSaturation: 1.3,
    },
  },
  {
    id: "blocks_dark",
    name: "Block Art",
    description: "Blok karakterlerle modern pixelart",
    icon: "🔳",
    bg: "#111111",
    fg: "#eeeeee",
    settings: {
      charsetId: "blocks",
      background: "#111111",
      foreground: "#eeeeee",
      mode: "mono",
      contrast: 1.3,
      brightness: 0,
      invert: false,
      fontSize: 12,
    },
  },
  {
    id: "hacker",
    name: "Hacker Mode",
    description: "Binary 0/1 hacker estetiği",
    icon: "💻",
    bg: "#050505",
    fg: "#39ff14",
    settings: {
      charsetId: "binary",
      background: "#050505",
      foreground: "#39ff14",
      mode: "mono",
      contrast: 1.5,
      brightness: 0,
      invert: false,
      fontSize: 10,
    },
  },
];
